"""Subprocess entry points for cross-process storage tests.

Run as ``python -m tests.storage._proc <command> ...`` from the repository
root. Each command opens its own ``CorpusStorageContext`` (a separate OS
process from the test), prints one JSON line, and exits. Identities arrive as
raw hex of a key generated by the test for this run only.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import UTC, datetime
from typing import Any

from folio_insights.revision import edit_shard_content
from folio_insights.storage import CorpusStorageContext

from tests.storage.conftest import (
    Identity,
    at,
    genesis,
    new_identity,
    role_assertion,
    shard,
)


async def _write(root: str, corpus: str, admin_hex: str) -> dict[str, Any]:
    admin = Identity.from_raw_hex(admin_hex)
    reviewer = new_identity()
    ctx = await CorpusStorageContext.open(root, corpus)
    try:
        g = await ctx.governance.append(genesis(corpus, admin))
        r = await ctx.governance.append(
            role_assertion(corpus, admin, reviewer.did, "reviewer", at(10))
        )
        base = shard(1)
        dependent = shard(2, depends_on_shards=[base.shard_iri])
        await ctx.shards.put(base.shard_iri, base)
        await ctx.shards.put(dependent.shard_iri, dependent)
        await edit_shard_content(
            base.shard_iri,
            "sense",
            "synthetic revised sense",
            admin.did,
            "synthetic revision",
            admin.sk,
            ctx.shards,
        )
        status = await ctx.status()
    finally:
        await ctx.close()
    return {
        "positions": [g.position, r.position],
        "reviewer": reviewer.did,
        "base": base.shard_iri,
        "dependent": dependent.shard_iri,
        "journal_head": status.journal_head,
    }


async def _read(root: str, corpus: str) -> dict[str, Any]:
    ctx = await CorpusStorageContext.open(root, corpus)
    try:
        status = await ctx.status()
        events = [
            {"position": e.position, "action": e.action}
            async for e in ctx.governance.iter_events(corpus)
        ]
        roles = await ctx.governance.query_active_roles_at(
            corpus, datetime(2100, 1, 1, tzinfo=UTC)
        )
        shards = {s.shard_iri: s.sense async for s in ctx.shards.iter_shards()}
        dependents: dict[str, list[str]] = {}
        for iri in shards:
            dependents[iri] = [d.shard_iri for d in await ctx.shards.dependents_of(iri)]
        triples = await ctx.query("SELECT (COUNT(*) AS ?n) WHERE { ?s ?p ?o }")
        return {
            "journal_head": status.journal_head,
            "watermark": status.projection_watermark,
            "events": events,
            "roles": {did: sorted(r) for did, r in roles.items()},
            "shards": shards,
            "dependents": dependents,
            "triple_count": int(triples[0]["n"].value),
        }
    finally:
        await ctx.close()


async def _compete(
    root: str, corpus: str, admin_hex: str, worker: str, count: int
) -> dict[str, Any]:
    admin = Identity.from_raw_hex(admin_hex)
    ctx = await CorpusStorageContext.open(root, corpus)
    positions: list[int] = []
    shard_iris: list[str] = []
    try:
        for i in range(count):
            subject = new_identity()
            event = await ctx.governance.append(
                role_assertion(corpus, admin, subject.did, "reviewer", at(100))
            )
            positions.append(event.position)
            s = shard(int(worker) * 1000 + i)
            await ctx.shards.put(s.shard_iri, s)
            shard_iris.append(s.shard_iri)
    finally:
        await ctx.close()
    return {"worker": worker, "positions": positions, "shards": shard_iris}


async def _crash(root: str, corpus: str, admin_hex: str) -> None:
    """Commit to the journal, then die before the projection catches up."""
    admin = Identity.from_raw_hex(admin_hex)
    subject = new_identity()
    ctx = await CorpusStorageContext.open(root, corpus)

    async def _die(self: CorpusStorageContext, op_id: str, position: int) -> None:
        sys.stdout.write(json.dumps({"committed": position, "op_id": op_id}) + "\n")
        sys.stdout.flush()
        os._exit(17)

    CorpusStorageContext._after_commit = _die  # type: ignore[method-assign]
    await ctx.governance.append(
        role_assertion(corpus, admin, subject.did, "reviewer", at(20)), op_id="crash-op"
    )


def main(argv: list[str]) -> None:
    command, *args = argv
    if command == "write":
        out = asyncio.run(_write(*args))
    elif command == "read":
        out = asyncio.run(_read(*args))
    elif command == "compete":
        root, corpus, admin_hex, worker, count = args
        out = asyncio.run(_compete(root, corpus, admin_hex, worker, int(count)))
    elif command == "crash":
        asyncio.run(_crash(*args))
        raise SystemExit("crash command returned without exiting")
    else:
        raise SystemExit(f"unknown command {command!r}")
    print(json.dumps(out))


if __name__ == "__main__":
    main(sys.argv[1:])
