#!/usr/bin/env python3
"""Export the web image's install locks from ``uv.lock``.

WHY THIS EXISTS
---------------
``Dockerfile.web`` must install the same dependency set that ``uv.lock`` resolves
(the set local dev and the test suite run against), and it must do so with
``--require-hashes`` so a rebuild months later fetches byte-identical artifacts.
``uv export`` writes that set with every sha256 — except for git dependencies:
``folio-propositions`` is a git+https reference, a VCS checkout has no archive hash,
and ``uv pip install --require-hashes`` refuses any unhashed line. So the export is
split in two, both derived from ``uv.lock`` and nothing else:

``requirements.lock``
    Every third-party registry package in the web closure (``--no-dev``, project
    and VCS packages excluded), each with all of its sha256 hashes. Installed with
    ``--require-hashes --only-binary :all:``.

``requirements.vcs.lock``
    Each VCS dependency pinned to the full commit SHA ``uv.lock`` resolved. Installed
    with ``--no-deps``: its own dependencies are already in ``requirements.lock``,
    and the commit SHA is the content pin (a different tree cannot carry that SHA).

USAGE
-----
    # rewrite both files after `uv lock` changes uv.lock
    .venv/bin/python scripts/export_image_locks.py

    # exit 1 when the committed files are stale (CI / unit-test guard)
    .venv/bin/python scripts/export_image_locks.py --check

Needs the ``uv`` binary; no network (``uv export --frozen`` reads only uv.lock).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

REPO_ROOT = Path(__file__).resolve().parent.parent
UV_LOCK = "uv.lock"
REGISTRY_LOCK = "requirements.lock"
VCS_LOCK = "requirements.vcs.lock"

VCS_HEADER = (
    "# This file was autogenerated by scripts/export_image_locks.py from uv.lock.\n"
    "# VCS dependencies pinned to the commit uv.lock resolved; install with --no-deps\n"
    "# (their own dependencies are hash-pinned in requirements.lock).\n"
)


def vcs_packages(lock_path: Path) -> list[tuple[str, str]]:
    """Return ``(name, "name @ git+URL@<commit>")`` for each git package in uv.lock."""
    data = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    out: list[tuple[str, str]] = []
    for package in data.get("package", []):
        git = package.get("source", {}).get("git")
        if not git:
            continue
        parts = urlsplit(git)
        commit = parts.fragment
        if len(commit) != 40:
            raise SystemExit(
                f"error: uv.lock has no full commit SHA for {package['name']}: {git!r}"
            )
        # Drop the ?rev=<tag> query: the commit alone is the pin.
        url = urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
        out.append((package["name"], f"{package['name']} @ git+{url}@{commit}"))
    return sorted(out)


def render(repo_root: Path) -> dict[str, str]:
    """Return ``{filename: content}`` for both exported locks."""
    uv = shutil.which("uv")
    if uv is None:
        raise SystemExit("error: uv is not on PATH")
    vcs = vcs_packages(repo_root / UV_LOCK)
    cmd = [
        "uv", "export", "--frozen", "--no-dev", "--no-emit-project",
        "--format", "requirements-txt",
    ]
    for name, _ in vcs:
        cmd += ["--no-emit-package", name]
    registry = subprocess.run(
        [uv, *cmd[1:]], cwd=repo_root, capture_output=True, text=True, check=True,
    ).stdout
    if " @ " in registry:
        raise SystemExit("error: uv export still emitted a direct-URL requirement")
    vcs_text = VCS_HEADER + "".join(f"{line}\n" for _, line in vcs)
    return {REGISTRY_LOCK: registry, VCS_LOCK: vcs_text}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true",
        help="do not write; exit 1 if a committed lock differs from uv.lock",
    )
    args = parser.parse_args(argv)

    stale: list[str] = []
    for name, content in render(REPO_ROOT).items():
        path = REPO_ROOT / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            print(f"  unchanged {name}")
            continue
        stale.append(name)
        if args.check:
            print(f"  STALE     {name}")
        else:
            path.write_text(content, encoding="utf-8")
            print(f"  wrote     {name}")
    if args.check and stale:
        print("Run scripts/export_image_locks.py to regenerate.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
